### ISSUE TITLE
AttributeError: module 'scipy.integrate' has no attribute 'trapz'

### ISSUE THREAD

**Issue by zeyunZhao** [wmglab-duke/cajal#2]
I followed every step of yours and got AttributeError: module 'scipy.integrate' has no attribute 'trapz'. May I change them as follows?

# "trapezoid": integrate.trapz,
        # "composite_trapezoid": integrate.cumtrapz,
        # "composite_simpson": integrate.simps,
        # "romberg": integrate.romb,
        "trapezoid": integrate.trapezoid,
        "composite_trapezoid": integrate.cumulative_trapezoid,
        "composite_simpson": integrate.simpson,
        "romberg": integrate.romb,

**Comment by minhajh** [comment]
Yep, looks like SciPy API changes. Will be fixed in next commit.
